-- Idempotent apply of AddEventStorePhase7LeaseAndAttemptHistory (20260312100000).
-- Also adds EventStore columns required by Phase 7 code that may be missing if earlier
-- migrations (Phase 4, ProcessingStartedAtUtc) were not applied: NextRetryAtUtc,
-- PayloadVersion, ProcessingStartedAtUtc, and index IX_EventStore_Status_NextRetryAtUtc.
-- Use when Phase 7 is not in the discovered EF chain (no Designer) or when applying via script.
-- Safe to run multiple times.

-- EventStore: add columns if table exists and column not present (PostgreSQL 9.5+)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'EventStore') THEN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'EventStore' AND column_name = 'NextRetryAtUtc') THEN
      ALTER TABLE "EventStore" ADD COLUMN "NextRetryAtUtc" timestamp with time zone NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'EventStore' AND column_name = 'PayloadVersion') THEN
      ALTER TABLE "EventStore" ADD COLUMN "PayloadVersion" character varying(20) NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'EventStore' AND column_name = 'ProcessingStartedAtUtc') THEN
      ALTER TABLE "EventStore" ADD COLUMN "ProcessingStartedAtUtc" timestamp with time zone NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'EventStore' AND column_name = 'ProcessingNodeId') THEN
      ALTER TABLE "EventStore" ADD COLUMN "ProcessingNodeId" character varying(200) NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'EventStore' AND column_name = 'ProcessingLeaseExpiresAtUtc') THEN
      ALTER TABLE "EventStore" ADD COLUMN "ProcessingLeaseExpiresAtUtc" timestamp with time zone NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'EventStore' AND column_name = 'LastClaimedAtUtc') THEN
      ALTER TABLE "EventStore" ADD COLUMN "LastClaimedAtUtc" timestamp with time zone NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'EventStore' AND column_name = 'LastClaimedBy') THEN
      ALTER TABLE "EventStore" ADD COLUMN "LastClaimedBy" character varying(200) NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'EventStore' AND column_name = 'LastErrorType') THEN
      ALTER TABLE "EventStore" ADD COLUMN "LastErrorType" character varying(100) NULL;
    END IF;
  END IF;
END $$;

-- Phase 4 index (required for Claim/retry queries)
CREATE INDEX IF NOT EXISTS "IX_EventStore_Status_NextRetryAtUtc" ON "EventStore" ("Status", "NextRetryAtUtc");

-- Phase 7 index (stuck/lease expiry queries)
CREATE INDEX IF NOT EXISTS "IX_EventStore_Status_ProcessingLeaseExpiresAtUtc" ON "EventStore" ("Status", "ProcessingLeaseExpiresAtUtc");

-- EventStoreAttemptHistory table
CREATE TABLE IF NOT EXISTS "EventStoreAttemptHistory" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "EventId" uuid NOT NULL,
    "EventType" character varying(200) NOT NULL,
    "CompanyId" uuid NULL,
    "HandlerName" character varying(500) NOT NULL,
    "AttemptNumber" integer NOT NULL,
    "Status" character varying(50) NOT NULL,
    "StartedAtUtc" timestamp with time zone NOT NULL,
    "FinishedAtUtc" timestamp with time zone NULL,
    "DurationMs" integer NULL,
    "ProcessingNodeId" character varying(200) NULL,
    "ErrorType" character varying(100) NULL,
    "ErrorMessage" character varying(2000) NULL,
    "StackTraceSummary" character varying(2000) NULL,
    "WasRetried" boolean NOT NULL,
    "WasDeadLettered" boolean NOT NULL,
    CONSTRAINT "PK_EventStoreAttemptHistory" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_EventStoreAttemptHistory_EventId" ON "EventStoreAttemptHistory" ("EventId");
CREATE INDEX IF NOT EXISTS "IX_EventStoreAttemptHistory_EventId_AttemptNumber" ON "EventStoreAttemptHistory" ("EventId", "AttemptNumber");

-- Record migration as applied so EF Core and future scripts skip it
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260312100000_AddEventStorePhase7LeaseAndAttemptHistory', '10.0.0'
WHERE NOT EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312100000_AddEventStorePhase7LeaseAndAttemptHistory');
