using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CephasOps.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class PendingModelCheck : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // EventStore Phase 7 + EventStoreAttemptHistory: idempotent for DBs where Phase 7 was
            // already applied via script (e.g. apply-EventStorePhase7LeaseAndAttemptHistory.sql).
            migrationBuilder.Sql(@"
-- EventStore Phase 7 columns (ADD COLUMN IF NOT EXISTS for PostgreSQL 9.5+)
ALTER TABLE ""EventStore"" ADD COLUMN IF NOT EXISTS ""LastClaimedAtUtc"" timestamp with time zone NULL;
ALTER TABLE ""EventStore"" ADD COLUMN IF NOT EXISTS ""LastClaimedBy"" character varying(200) NULL;
ALTER TABLE ""EventStore"" ADD COLUMN IF NOT EXISTS ""LastErrorType"" character varying(100) NULL;
ALTER TABLE ""EventStore"" ADD COLUMN IF NOT EXISTS ""ProcessingLeaseExpiresAtUtc"" timestamp with time zone NULL;
ALTER TABLE ""EventStore"" ADD COLUMN IF NOT EXISTS ""ProcessingNodeId"" character varying(200) NULL;
ALTER TABLE ""EventStore"" ADD COLUMN IF NOT EXISTS ""ProcessingStartedAtUtc"" timestamp with time zone NULL;

CREATE TABLE IF NOT EXISTS ""EventStoreAttemptHistory"" (
    ""Id"" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ""EventId"" uuid NOT NULL,
    ""EventType"" character varying(200) NOT NULL,
    ""CompanyId"" uuid NULL,
    ""HandlerName"" character varying(500) NOT NULL,
    ""AttemptNumber"" integer NOT NULL,
    ""Status"" character varying(50) NOT NULL,
    ""StartedAtUtc"" timestamp with time zone NOT NULL,
    ""FinishedAtUtc"" timestamp with time zone NULL,
    ""DurationMs"" integer NULL,
    ""ProcessingNodeId"" character varying(200) NULL,
    ""ErrorType"" character varying(100) NULL,
    ""ErrorMessage"" character varying(2000) NULL,
    ""StackTraceSummary"" character varying(2000) NULL,
    ""WasRetried"" boolean NOT NULL,
    ""WasDeadLettered"" boolean NOT NULL,
    CONSTRAINT ""PK_EventStoreAttemptHistory"" PRIMARY KEY (""Id"")
);

CREATE INDEX IF NOT EXISTS ""IX_EventStoreAttemptHistory_EventId"" ON ""EventStoreAttemptHistory"" (""EventId"");
CREATE INDEX IF NOT EXISTS ""IX_EventStoreAttemptHistory_EventId_AttemptNumber"" ON ""EventStoreAttemptHistory"" (""EventId"", ""AttemptNumber"");
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
DROP TABLE IF EXISTS ""EventStoreAttemptHistory"";
ALTER TABLE ""EventStore"" DROP COLUMN IF EXISTS ""LastClaimedAtUtc"";
ALTER TABLE ""EventStore"" DROP COLUMN IF EXISTS ""LastClaimedBy"";
ALTER TABLE ""EventStore"" DROP COLUMN IF EXISTS ""LastErrorType"";
ALTER TABLE ""EventStore"" DROP COLUMN IF EXISTS ""ProcessingLeaseExpiresAtUtc"";
ALTER TABLE ""EventStore"" DROP COLUMN IF EXISTS ""ProcessingNodeId"";
ALTER TABLE ""EventStore"" DROP COLUMN IF EXISTS ""ProcessingStartedAtUtc"";
");
        }
    }
}
